server:
  port: 8080

spring:
  datasource: 
    url: jdbc:h2:file:./data/invoice-db;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.format_sql: true
    h2:
      console:
      enabled: true
      path: /h2-console
    main:
      banner-mode: "off"